<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="297mm"
   height="210mm"
   viewBox="0 0 1052.3622 744.09448"
   id="svg2"
   version="1.1"
   inkscape:version="0.91 r13725"
   sodipodi:docname="makefile.svg">
  <defs
     id="defs4">
    <linearGradient
       inkscape:collect="always"
       id="linearGradient4471">
      <stop
         style="stop-color:#ffc67d;stop-opacity:1"
         offset="0"
         id="stop4473" />
      <stop
         style="stop-color:#ffeed7;stop-opacity:1"
         offset="1"
         id="stop4475" />
    </linearGradient>
    <marker
       inkscape:stockid="TriangleInM"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="TriangleInM"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path8546"
         d="M 5.77,0.0 L -2.88,5.0 L -2.88,-5.0 L 5.77,0.0 z "
         style="fill-rule:evenodd;stroke:#6a6a6a;stroke-width:1pt;stroke-opacity:1;fill:#6a6a6a;fill-opacity:1"
         transform="scale(-0.4)" />
    </marker>
    <marker
       inkscape:stockid="Arrow2Mstart"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow2Mstart"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path8434"
         style="fill-rule:evenodd;stroke-width:0.625;stroke-linejoin:round;stroke:#3c00d4;stroke-opacity:1;fill:#3c00d4;fill-opacity:1"
         d="M 8.7185878,4.0337352 L -2.2072895,0.016013256 L 8.7185884,-4.0017078 C 6.9730900,-1.6296469 6.9831476,1.6157441 8.7185878,4.0337352 z "
         transform="scale(0.6) translate(0,0)" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Sstart"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow1Sstart"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path8422"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         style="fill-rule:evenodd;stroke:#3c00d4;stroke-width:1pt;stroke-opacity:1;fill:#3c00d4;fill-opacity:1"
         transform="scale(0.2) translate(6,0)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="TriangleOutM"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path4644"
         d="M 5.77,0.0 L -2.88,5.0 L -2.88,-5.0 L 5.77,0.0 z "
         style="fill-rule:evenodd;stroke:#ff0101;stroke-width:1pt;stroke-opacity:1;fill:#ffffff;fill-opacity:1"
         transform="scale(0.4)" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Send"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="marker4871"
       style="overflow:visible;"
       inkscape:isstock="true">
      <path
         id="path4873"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#000000;fill-opacity:1"
         transform="scale(0.2) rotate(180) translate(6,0)" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Send"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow1Send"
       style="overflow:visible;"
       inkscape:isstock="true">
      <path
         id="path4514"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#000000;fill-opacity:1"
         transform="scale(0.2) rotate(180) translate(6,0)" />
    </marker>
    <marker
       inkscape:stockid="DiamondS"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="DiamondS"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path4584"
         d="M 0,-7.0710768 L -7.0710894,0 L 0,7.0710589 L 7.0710462,0 L 0,-7.0710768 z "
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#000000;fill-opacity:1"
         transform="scale(0.2)" />
    </marker>
    <marker
       inkscape:stockid="Arrow2Mend"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow2Mend"
       style="overflow:visible;"
       inkscape:isstock="true">
      <path
         id="path4526"
         style="fill-rule:evenodd;stroke-width:0.625;stroke-linejoin:round;stroke:#0000ff;stroke-opacity:1;fill:#0000ff;fill-opacity:1"
         d="M 8.7185878,4.0337352 L -2.2072895,0.016013256 L 8.7185884,-4.0017078 C 6.9730900,-1.6296469 6.9831476,1.6157441 8.7185878,4.0337352 z "
         transform="scale(0.6) rotate(180) translate(0,0)" />
    </marker>
    <marker
       inkscape:stockid="Arrow2Lend"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow2Lend"
       style="overflow:visible;"
       inkscape:isstock="true">
      <path
         id="path4520"
         style="fill-rule:evenodd;stroke-width:0.625;stroke-linejoin:round;stroke:#000000;stroke-opacity:1;fill:#000000;fill-opacity:1"
         d="M 8.7185878,4.0337352 L -2.2072895,0.016013256 L 8.7185884,-4.0017078 C 6.9730900,-1.6296469 6.9831476,1.6157441 8.7185878,4.0337352 z "
         transform="scale(1.1) rotate(180) translate(1,0)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-1"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-0"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#00d401;fill-opacity:1;fill-rule:evenodd;stroke:#00d401;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3-3"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2-6"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#00d401;fill-opacity:1;fill-rule:evenodd;stroke:#00d401;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3-3-6"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2-6-2"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#00d401;fill-opacity:1;fill-rule:evenodd;stroke:#00d401;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-8"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-4"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#ff0101;fill-opacity:1;fill-rule:evenodd;stroke:#ff0101;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3-3-61"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2-6-8"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#00d401;fill-opacity:1;fill-rule:evenodd;stroke:#00d401;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3-3-61-9"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2-6-8-2"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#3c00d4;fill-opacity:1;fill-rule:evenodd;stroke:#3c00d4;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-3-3-61-9-9"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-2-6-8-2-7"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#6a6a6a;fill-opacity:1;fill-rule:evenodd;stroke:#6a6a6a;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4953"
       id="linearGradient4345"
       x1="377.99991"
       y1="772.36218"
       x2="377.99991"
       y2="592.36218"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0.85033859,0,0,0.44412174,5.7448776,629.61651)" />
    <linearGradient
       inkscape:collect="always"
       id="linearGradient4953">
      <stop
         style="stop-color:#7fff7f;stop-opacity:1"
         offset="0"
         id="stop4955" />
      <stop
         style="stop-color:#d7ffd7;stop-opacity:1"
         offset="1"
         id="stop4957" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4953"
       id="linearGradient4570"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0.85033859,0,0,0.44412174,5.7448776,629.61651)"
       x1="377.99991"
       y1="772.36218"
       x2="377.99991"
       y2="592.36218" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4471"
       id="linearGradient4642"
       gradientUnits="userSpaceOnUse"
       x1="326"
       y1="974.36218"
       x2="326"
       y2="894.36218"
       gradientTransform="translate(-76,-280)" />
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4953"
       id="linearGradient5205"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0.89311003,0,0,0.44412174,-9.0497441,629.61651)"
       x1="377.99991"
       y1="772.36218"
       x2="377.99991"
       y2="592.36218" />
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-5"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-3"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
    <linearGradient
       id="linearGradient4947"
       inkscape:collect="always">
      <stop
         id="stop4949"
         offset="0"
         style="stop-color:#a79bff;stop-opacity:1" />
      <stop
         id="stop4951"
         offset="1"
         style="stop-color:#edebff;stop-opacity:1" />
    </linearGradient>
    <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4947"
       id="linearGradient5415"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(0.89311003,0,0,0.44412174,-9.0497441,629.61651)"
       x1="377.99991"
       y1="772.36218"
       x2="377.99991"
       y2="592.36218" />
    <marker
       inkscape:stockid="TriangleOutM"
       orient="auto"
       refY="0"
       refX="0"
       id="TriangleOutM-0-6"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path4644-3-29"
         d="m 5.77,0 -8.65,5 0,-10 8.65,5 z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="scale(0.4,0.4)" />
    </marker>
  </defs>
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="1"
     inkscape:cx="531.73053"
     inkscape:cy="700.63532"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="true"
     inkscape:window-width="1855"
     inkscape:window-height="1056"
     inkscape:window-x="65"
     inkscape:window-y="24"
     inkscape:window-maximized="1">
    <inkscape:grid
       type="xygrid"
       id="grid4136" />
  </sodipodi:namedview>
  <metadata
     id="metadata7">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
        <dc:creator>
          <cc:Agent>
            <dc:title>Luca Ceresoli</dc:title>
          </cc:Agent>
        </dc:creator>
        <dc:date>2017</dc:date>
        <cc:license
           rdf:resource="http://creativecommons.org/licenses/by-sa/3.0/" />
      </cc:Work>
      <cc:License
         rdf:about="http://creativecommons.org/licenses/by-sa/3.0/">
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#Reproduction" />
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#Distribution" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#Notice" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#Attribution" />
        <cc:permits
           rdf:resource="http://creativecommons.org/ns#DerivativeWorks" />
        <cc:requires
           rdf:resource="http://creativecommons.org/ns#ShareAlike" />
      </cc:License>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Livello 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(0,-308.26772)">
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="290"
       y="852.36218"
       id="text8270"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         id="tspan8272"
         x="290"
         y="852.36218" /></text>
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="880"
       y="972.36218"
       id="text5047"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         id="tspan5049"
         x="880"
         y="972.36218" /></text>
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="579.28571"
       y="571.19745"
       id="text5099-0-3-1-5"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="579.28571"
         y="571.19745"
         style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:center;text-anchor:middle"
         id="tspan4961-6-2-4" /></text>
    <g
       id="g4662"
       transform="translate(-13.458405,0.89949498)">
      <rect
         rx="19.396936"
         ry="19.396936"
         y="612.96527"
         x="223.87659"
         height="79.674088"
         width="258.45285"
         id="rect5002-60-7"
         style="opacity:1;fill:url(#linearGradient4642);fill-opacity:1;fill-rule:nonzero;stroke:#ab6000;stroke-width:3.00000048;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
      <text
         sodipodi:linespacing="125%"
         id="text5099-0-3-9-8-3-6-9"
         y="671.44238"
         x="242.0766"
         style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         xml:space="preserve"><tspan
           id="tspan4961-6-1-7-6-2-2"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:start;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-opacity:1"
           y="671.44238"
           x="242.0766"
           sodipodi:role="line">hello</tspan></text>
    </g>
    <g
       id="g4499"
       transform="matrix(1.0386918,0,0,1,-251.50225,-539.31371)">
      <g
         id="g5168">
        <rect
           style="opacity:1;fill:url(#linearGradient4345);fill-opacity:1;fill-rule:nonzero;stroke:#006200;stroke-width:2.94359446;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
           id="rect5002"
           width="258.45285"
           height="79.674088"
           x="299.87659"
           y="892.96527"
           ry="19.396936"
           rx="18.674391" />
        <text
           xml:space="preserve"
           style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
           x="318.0766"
           y="951.44244"
           id="text5099-0-3-9-8-3"
           sodipodi:linespacing="125%"><tspan
             sodipodi:role="line"
             x="318.0766"
             y="951.44244"
             style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:start;text-anchor:start"
             id="tspan4961-6-1-7-6">hello.c</tspan></text>
      </g>
    </g>
    <g
       transform="translate(8.000003,99.999997)"
       id="g4499-9" />
    <g
       transform="matrix(1.0309534,0,0,1,43.818299,-539.31371)"
       id="g4499-3">
      <rect
         rx="18.814562"
         ry="19.396936"
         y="892.96527"
         x="299.87659"
         height="79.674088"
         width="258.45285"
         id="rect5002-60"
         style="opacity:1;fill:url(#linearGradient4570);fill-opacity:1;fill-rule:nonzero;stroke:#006200;stroke-width:2.95462108;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
      <text
         sodipodi:linespacing="125%"
         id="text5099-0-3-9-8-3-6"
         y="951.44244"
         x="318.0766"
         style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         xml:space="preserve"><tspan
           id="tspan4961-6-1-7-6-2"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:start;text-anchor:start"
           y="951.44244"
           x="318.0766"
           sodipodi:role="line">utils.c</tspan></text>
    </g>
    <g
       transform="translate(342.10051,-539.31371)"
       id="g5373">
      <rect
         rx="19.396936"
         ry="19.396936"
         y="892.96527"
         x="299.87659"
         height="79.674088"
         width="271.45285"
         id="rect5002-60-9"
         style="opacity:1;fill:url(#linearGradient5205);fill-opacity:1;fill-rule:nonzero;stroke:#006200;stroke-width:3.00000048;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
      <text
         sodipodi:linespacing="125%"
         id="text5099-0-3-9-8-3-6-1"
         y="951.44244"
         x="318.0766"
         style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;text-align:start;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         xml:space="preserve"><tspan
           id="tspan4961-6-1-7-6-2-27"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:start;text-anchor:start"
           y="951.44244"
           x="318.0766"
           sodipodi:role="line">Makefile</tspan></text>
    </g>
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:6;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-0-5)"
       d="m 339.21311,552.38142 c 0,47.55022 0,47.55022 0,47.55022"
       id="path4667-3"
       inkscape:connector-curvature="0" />
    <g
       transform="translate(-95.958405,-420.31371)"
       id="g5373-7">
      <rect
         rx="0"
         ry="0"
         y="892.96527"
         x="299.87659"
         height="79.674088"
         width="271.45285"
         id="rect5002-60-9-5"
         style="opacity:1;fill:url(#linearGradient5415);fill-opacity:1;fill-rule:nonzero;stroke:#0a0062;stroke-width:3.00000048;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
      <text
         sodipodi:linespacing="125%"
         id="text5099-0-3-9-8-3-6-1-3"
         y="951.44244"
         x="435.7373"
         style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;text-align:center;letter-spacing:0px;word-spacing:0px;writing-mode:lr-tb;text-anchor:middle;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
         xml:space="preserve"><tspan
           id="tspan4961-6-1-7-6-2-27-5"
           style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:50px;font-family:'DejaVu Sans Mono';-inkscape-font-specification:'DejaVu Sans Mono';text-align:center;text-anchor:middle"
           y="951.44244"
           x="435.7373"
           sodipodi:role="line">make</tspan></text>
    </g>
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:5.99999952;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-0)"
       d="m 270,432.36222 0,29.55112"
       id="path5429"
       inkscape:connector-curvature="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:5.99999952;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-0-6)"
       d="m 420.61374,432.36222 0,29.55112"
       id="path5429-1"
       inkscape:connector-curvature="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:6;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:6,6;stroke-opacity:1;marker-end:url(#TriangleOutM-0-1);stroke-dashoffset:0"
       d="m 779.83272,432.36221 0,80 -290.89333,0"
       id="path6638"
       inkscape:connector-curvature="0" />
  </g>
</svg>
